
backend = "resized"
color_space = "labmixed"

palette = "dark"
check_contrast = true

[templates]
quickshell = { template = 'quickshell.json', target = '~/zenflow/quickshell/Settings/Theme.json' }
gtk3 = { template = 'gtk-colors.css', target = "~/.config/gtk-3.0/custom-colors.css"}
gtk4 = { template = 'gtk-colors.css', target = "~/.config/gtk-4.0/custom-colors.css"}

midnight-discord = { template = 'midnight-discord.css', target = "~/.config/equibop/themes/colored-midnight.css"}
cava = { template = 'cava-colors', target = "~/.config/cava/config"}
yazi = { template = 'yazi-colors.toml', target = "~/.config/yazi/yazi-colors.toml"}
ohmyposh = {template = 'oh-my-posh.toml', target = "~/.config/ompsh/theme.toml"}
foot = {template = 'foot.ini', target = "~/.config/foot/foot.ini"}
zellij = {template = 'zentheme.kdl', target = "~/.config/zellij/themes/zentheme.kdl"}
logseq = {template = 'zenseq.css', target = "~/zadome/logseq/custom.css"}
